# Generated by Django 5.1.6 on 2025-03-01 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0001_initial'),
    ]

    operations = [
    ]
