# Generated by Django 5.1.6 on 2025-03-02 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0003_alter_task_fecha_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='estado',
        ),
    ]
